[tool.poetry]
name = "steelpy"
version = "0.1.1"
description = "A simple library for section properties of AISC steel shapes"
authors = ["evanfaler <emfaler@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pandas = "^2.2.2"
openpyxl = "^3.1.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
