[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"


[project]
name = "vloc_plugin"
version = "0.0.6"
urls = { GitHub = "https://github.com/linyeh1129/vloc_plugin" }
authors = [{ name = 'Lin Yeh', email = 'lin_yeh@outlook.com' }]
description = "Plugin functions for vloc"
readme = "README.md"
requires-python = ">=3.10"
license = { text = "MIT" }
keywords = ['ui aumomation', 'computer vision']
classifiers = ['Programming Language :: Python :: 3']
