[tool.poetry]
name = "kkpyai"
version = "0.5.0"
description = "Utility over popular low-level AI API"
authors = ["Beinan Li <li.beinan@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
kkpyutil = "*"
matplotlib = "*"
torch = "*"
tensorflow = "*"

[tool.poetry.dev-dependencies]
pytest = "*"
coverage = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
