[build-system]
requires = [
    "setuptools>=61.0",
    "pybind11"
    ]
build-backend = "setuptools.build_meta"


[project]
name = "ximreader"
version = "1.0.1"
authors = [
    {name="Dinesh Kumar", email="dkumar@lbl.gov"},
    ]
description = "Python extension for reading xim files"
readme = "README.md"
license = {file = "LICENSE.txt"}
requires-python = ">=3.8"
dependencies = [ "numpy" ]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/aryabhatt/ximreader"
Issues = "https://github.com/aryabhatt/ximreader/issues"

