# SPDX-FileCopyrightText: 2022 Alec Delaney, written for Adafruit Industries
# SPDX-FileCopyrightText: Copyright (c) 2024 Steffen Kreutz
#
# SPDX-License-Identifier: MIT

[build-system]
requires = [
    "setuptools",
    "wheel",
    "setuptools-scm",
]

[project]
name = "circuitpython-mcp48xx"
description = "CircuitPython library for the MCP4801, MCP4811, MCP4821, MCP4802, MCP4812, and MCP4822 digital to analog converters."
version = "1.0.1"
readme = "README.rst"
authors = [
    {name = "Steffen Kreutz", email = "brushmate@gmail.com"}
]
urls = {Homepage = "https://github.com/brushmate/CircuitPython_MCP48XX"}
keywords = [
    "adafruit",
    "blinka",
    "circuitpython",
    "micropython",
    "mcp4801",
    "mcp4811",
    "mcp4821",
    "mcp4802",
    "mcp4812",
    "mcp4822",
]
license = {text = "MIT"}
classifiers = [
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Embedded Systems",
    "Topic :: System :: Hardware",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
]
dynamic = ["dependencies", "optional-dependencies"]

[tool.setuptools]
py-modules = ["mcp48xx"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}
optional-dependencies = {optional = {file = ["optional_requirements.txt"]}}
