[tool.poetry]
name = "maturin-watchdog"
version = "0.1.20"
description = "Build via maturin when changes are detected"
authors = ["Jocelyn-Gas <jocelyn.gas@dillygence.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
poetry = "^1.8.2"
python-dotenv = "^1.0.1"

[tool.poetry.group.dev.dependencies]
ruff = "^0.3.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins."poetry.application.plugin"]
maturin-watchdog = "maturin_watchdog.plugin:PoetryPlugin"