[tool.poetry]
name = "coinpaprika-async"
version = "3.1.1"
description = "An asynchronous library for interacting with the Coinpaprika.com API, written with httpx in Python."
authors = ["DroidZed <41507665+DroidZed@users.noreply.github.com>"]
readme = "README.md"
packages = [{ include = "coinpaprika_async_client" }]

[tool.poetry.dependencies]
python = "^3.11"
httpx = { extras = ["http2"], version = "^0.27.0" }

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.7.0"
black = "^24.3.0"
isort = "^5.13.2"
mypy = "^1.9.0"

[tool.poetry.group.test.dependencies]
pytest = "^8.1.1"
pytest-httpx = "^0.30.0"
pytest-asyncio = "^0.23.6"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 80
target-version = ['py311']
include = '\.pyi?$'

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88

[tool.mypy]
disallow_untyped_defs = true
show_error_context = true
warn_return_any = true

[tool.pytest]
minversion = 6.0
addopts = "-ra -q"
testpaths = ["tests"]
asyncio_mode = "strict"
