[tool.poetry]
name = "img2desmos"
version = "0.1.1"
description = "CLI tool to convert images to the LaTeX bezier curves formulas"
authors = ["Perchinka <aleksei.v.lukin@gmail.com>"]
readme = "README.md"
packages = [
    { include = "img2desmos" }
]

[tool.poetry.dependencies]
python = ">=3.9"
"svg.path" = "^6.3"
typer = "^0.12.3"
pyperclip = "^1.8.2"
cv = "^1.0.0"
sympy = "^1.12"
opencv-python = "^4.9.0.80"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
img2desmos = "img2desmos.main:start"
