[build-system]
requires = [
    "pip",
    "pygame",
    "setuptools>=61.0"
]
build-backend = "setuptools.build_meta"

[project]
name = "endersutils"
version = "0.5.1"
authors = [
  { name="EnderGames", email="business.endergames@gmail.com" },
]
description = "Some utility commands that aren't really too useful but I use them a lot."
readme = "README.md"
requires-python = ">=3.0.0, <3.12.0"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[tool.setuptools.packages.find]
where = ["src"]
exclude = ["tests*", "*.tests*", "indev*", "*.indev*", "eutils.txt", "__pycache__*"]