[tool.poetry]
name = "lineartest"
version = "0.4.1"
description = "A testing framework working with Starlette TestClient."
authors = ["Philip Fan <topfyf@qq.com>"]
readme = "README.md"
license = "MIT"

classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13"
]

[tool.poetry.dependencies]
python = "^3.10"
pydantic = "^2.6.4"
pyyaml = "^6.0.1"
httpx = "^0.27.0"


[tool.poetry.group.dev.dependencies]
commitizen = "^3.21.3"
ruff = "^0.3.5"
pre-commit = "^3.7.0"
isort = "^5.13.2"
mkdocs = "^1.5.3"
mkdocs-material = "^9.5.17"
starlette = "^0.37.2"


[tool.poetry.group.test.dependencies]
fastapi = "^0.110.1"
python-multipart = "^0.0.9"
starlette = "^0.37.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff.format]
quote-style = "single"

[tool.commitizen]
retry_after_failture = true
major_version_zero = true
