[tool.poetry]
name = "challengerteco"
version = "0.1.19"
description = "Clase para manejo de challenger en la nube"
authors = ["Eduardo Pagnone <mlopsaa@teco.com.ar>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
