[build-system]
requires = ["setuptools>=66.1.0"]
build-backend = "setuptools.build_meta"

[project]
name = "timeseries-etl-utils"
version = "0.0.1"
description = "Utility functions to create features from timeseries data"
readme = "README.md"
dependencies = [
    "numpy",
    "pandas",
    "openpyxl",
    "xlsxwriter"
]

[project.optional-dependencies]
test = [
    "pytest",
]
dev = [
    "mypy",
]

[tool]

[tool.black]
line-length = 88
