#[build-system]
#requires = ["setuptools", "wheel"]
#build-backend = "setuptools.build_meta"
[project]
name = "mucstpy"
version = "1.0.2"

[tool.poetry.dependencies]
python = "^3.8"
scanpy = "^1.9.3"
numpy = "*"
pandas = "*"
anndata = "*"
matplotlib = "*"
scipy = "*"
scikit-learn = "*"
psutil = "*"
tqdm = "*"
leidenalg = "*"
torch = "^2.0"
torchvision = "*"
torchtoolbox = {git = "https://github.com/bbchond/torch-toolbox.git", branch  = "master"}


authors = [
  { name="Yu Wang", email="qq352542417@gmail.com" },
]
description = "The initial package of MuCST"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/xkmaxidian/MuCST"
Issues = "https://github.com/xkmaxidian/MuCST/issues"